name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Bla bla
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: gh api repos/sz-coder/xml-parsing-test --method PATCH --field 'default_branch=master'

    - name: Run CI-Script
      run: php test.php && sleep 10 && touch abc

  check:
    name: Bla bada
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: ls -la
